apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.default.acme.email=morettiadne1@gmail.com"
      - "--certificatesresolvers.default.acme.storage=/data/acme.json"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
ports:
  web:
    port: 80
    targetPort: 80
    nodePort: 31571
    exposedPort: 80
  websecure:
    port: 443
    targetPort: 443
    nodePort: 30180
    exposedPort: 443
    tls:
      enabled: true

providers:
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: false

additionalArguments: 
  - "--entryPoints.web.address=:80"
  - "--entryPoints.websecure.address=:443"
  - "--certificatesresolvers.myresolver.acme.email=morettiadne1@gmail.com"
  - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
  - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
ports:
  web:
    port: 80
    targetPort: 80
    nodePort: 30854
    exposedPort: 80
  websecure:
    port: 443
    targetPort: 443
    nodePort: 30386
    exposedPort: 443
    tls:
      enabled: true

providers:
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: false
