apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-volume-claim
  labels:
    app: catalog-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi