apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-volume-claim
  labels:
    app: order-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi